# Generated by Django 4.1.2 on 2022-10-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_product_link_remove_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
